#Select the url, username and password for the application
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
username = Admin
password = admin123
dir = C:\\Dulini\\Studies\\SeleniumAutomation\\orangehrmautomation\\src\\main\\resources\\screenshots

#Select the browser (chrome, firefox, edge)
browser = chrome